### ISSUE TITLE
Options for highlighting hidden stairs and peaceful monsters

### ISSUE THREAD

**Issue by transcendreamer** [NullCGT/SpliceHack#140]
Quality-of-life suggestions:

- hilite hidden stairs : because stairs are not visible when objects are lying over and even not searchable with "_" command
- hilite peaceful monsters : because it is easy to shoot peaceful monster indistinguishable from hostile one

e.g. these are already implemented in dnethack

**Comment by copperwater** [comment]
The hilite_hidden_stairs option has been kind of superseded by #terrain in 3.6 variants. You can just look at the map without objects on it. Also, provided you have seen the stairs already, _> or _< should work to put your cursor there...

I thought Splice already had an option to underline peaceful monsters (don't want to hilite them because then you confuse them with pets), but maybe I was mistaken.

**Comment by transcendreamer** [comment]
For example xnethack has such option (hilite_hidden_stairs) being a fork of 3.6 (or 3.7 already).

#terrain really helps. Never used it before. Thanks.

Underlining peaceful would be excellent. Currently I don't see any differences between hostile and peaceful. Using curses mode.

**Comment by copperwater** [comment]
xnethack has hilite_hidden_stairs but it's in TTY only. It doesn't exist in any vanilla version, and I'm not inclined to continue supporting it if the devteam isn't biting.

**Comment by transcendreamer** [comment]
Yes, you are right.
