### ISSUE TITLE
Suggestion: Vampire race and firearms+grenades and Cthulhu from Slash'em

### ISSUE THREAD

**Issue by transcendreamer** [NullCGT/SpliceHack#39]
Hello, Splicehack gives a lot of fun, and it has "kitchen sink" conception, so I think adding some features from Slash'em would add even more fun, I recall it was a nice hardcore madness playing vampire and suck blood from enemies and even from peaceful citizens, as well as firing from rifles/pistols/etc and throwing grenades...

Some would say that firearms are anachronism for nethack "middle ages" -- but I would answer: lets look at dnethack (and notdnethack) where pirates use old-fashioned flintlocks / pistols while grenades were invented even earlier than firearms.

As for Cthulhu (and other Old Ones) - it's actually from unnethack and/or "lethe" patch adding some touch of lovecraftian horror atmosphere, also abovementioned dnethack also has a lot from Lovecraft's horrors.

With best regards...

**Comment by NullCGT** [comment]
Hiya! Since SpliceHack has been slowly transforming into something vaguely similar to Slash'em 3.6, I've actually given thought to all of these features in the past. Here are my opinions:

1. Vampire and doppelgänger races are partially implemented in the code, but there was a ton of conflict between the vampire and doppelgänger code in Slash'em and the vanilla code for 3.6. I want to add both of them in the near future, but they're larger undertakings than they initially appear.

2. One of my design goals for SpliceHack is to keep things relatively similar to the "mood" set by vanilla NetHack. Whether I've been successful at that is debatable at best, but it's still something I consider when adding new features. As such, I'm pretty strongly against adding firearms to the degree that Slash'em did. They feel too modern to me. 
That said, thank you for reminding me about flintlock pistols, because I do want to add them. They're fun and thematic, and make total sense given that there are pirates. Plus, the object materials patch by aosdict would play really nicely with pistols. Silver bullets and golden guns, here we come.
I have mixed feelings on grenades. On one hand, they're easily one of the most fun parts of playing Slash'em. They're incredibly satisfying to use, and they add a lot of interesting dynamics to combat. On the other, I've never liked how liberal Slash'em is with giving the player grenades. After fighting just a few soldiers, you have enough to last almost the entire game! If I add grenades, I want to make them a lot less common, and possibly expand them. What about different types of grenades? That would be a lot of fun. What about grenades that can be set off while they're in the player's inventory? That would be even more fun.

3. I'm actually working on slowly implementing parts of the Lethe patch right now! I'm not totally on board with how parts of it are implemented, so I've been going through and picking out the things that I want. I've never actually fought Cthulhu in Slash'em, so I've been hesitant to add them since I don't want to break balance.

**Comment by transcendreamer** [comment]
Great! Thanks for your detailed answer! I agree that balance is important, speaking of which, Slashem was actually horribly unbalanced, very hard from the start, and even in the mid-game it was possible to die very randomly. On the contrast, dNethack has much more smoother gameplay, and someone said on reddit - when you die - you die justifiably, it makes sense, not just because of unbalanced random.

> Silver bullets and golden guns, here we come.
Yeees, that's it!

>I'm pretty strongly against adding firearms to the degree that Slash'em did.
Ok, machine-guns and rocket launcher were really out of fantasy setting and totally overpowered. Still there are some strange things from future within vanilla nethack like quantum mechanics. Also, in dNethack we have anachronaut role starting with futuristic gadgets like lasers, etc, though it's legitimate according to the wiki as based on sci-fi elements in D&D namely "Expedition to the Barrier Peaks".

>If I add grenades, I want to make them a lot less common, and possibly expand them.
Yes, because visiting Fort/Barracks will stimulate grenade "grinding". What about crafting grenades? Not sure what it would cost to implement crafting in nethack without ruining the code, but crafting would probably look nice with material patch? Probably we always dreamed to have ability to be able to craft things in nethack, even maybe forging weapons and armor? We have already furnaces in Splicehack, maybe it could be used to consume materials to make new items? It would be a revolution in nethack world! )))

> What about different types of grenades? 
Also I recall ancient grenades in Assassin's Creed, it was different types of grenades and it was cool for adding tactical features to the battle, like smoke grenades for disorienting enemies and running away... and caltrops grenades to slowing enemies and giving them a little damage when they step on caltrops, also were blinding grenades and incendiary grenades types if I remember right. Probably the grenade's action could be combined with nethack's monster statuses like "slowed", "confused", "blind", etc. Also some grenade types could generate a "stinking cloud" which is already implemented in the nethack code. The same for the player if grenade is blasted at him/her location.

>about flintlock pistols, because I do want to add them
Cool! Also probably arquebus/musket would be a good candidates for thematic firearms? They're ancient enough like flintlock pistols.

>I'm actually working on slowly implementing parts of the Lethe patch right now!
That's great! impatiently waiting )))

>I've never actually fought Cthulhu in Slash'em, so I've been hesitant to add
The idea of adding Cthulhu is basically putting unmatched horror for the player, He is slow, but He is terribly strong, **and He is coming.**  ))) That's it. Inevitability. The feeling of suspense, like in good horror movies, when something is going nearer and nearer but still it's not the end. Ideally the player would still having a hope to escape, Cthulhu is chasing, but @ is bit faster, so the key point is not letting Him to catch @ in a corner or in a deadlock corridor. By the way, it looks a good idea (probably) to make a reference to "At the Mountains of Madness" when @ is going through a corridor and hears "Tekeli" and sees some lights and shoggots are starting to chase @... Back to Cthulhu, I'm not welcoming instadeath attacks - that's not actually horror. But the idea that Cthulhu even rise after after death again (after some time) to pursue player is really Lovecraftian horror (like in the story of Johansen in "The Call of Cthulhu") Draining intelligence/wisdom would be also according to Lovecraft's unspeakable horror when character is loosing his mind (if Cthulhu is face-to-face). Actually I never fought Cthulhu in slashem but I did in unNethack and practically He can not be vanquished in honest fight, only by meas of Wand of Death, that's probably not good. dNethack's Cthulhu looks more interesting and could be beaten by ranged attacks but I haven't reach him yet. (((

Sorry for the long post. I would be happy if you find some of my humble ideas worth considering. Kind regards.

**Comment by NullCGT** [comment]
>Slashem was actually horribly unbalanced, very hard from the start, and even in the mid-game it was possible to die very randomly. 
I love Slash'em with all my heart, but I completely agree. There's a lot of features which are just incredibly unbalanced and warp the game. Extremely common wands of create horde which are more powerful when used by monsters, titans being included in summon nasties, the abundance of toilets, and monsters being able to zap the player with wands of draining, just to name a few things. Generally when I pull something from Slash'em, I make some small changes to make it less likely to cause random deaths. For example, I significantly dropped the rarity of wand of create horde and nerfed the number of monsters it creates when used by an enemy.
> based on sci-fi elements in D&D namely "Expedition to the Barrier Peaks".
Expedition to the Barrier Peaks is an awesome adventure! It would be fun to add a level that's a homage to that.
> Probably we always dreamed to have ability to be able to craft things in nethack, even maybe forging weapons and armor? We have already furnaces in Splicehack, maybe it could be used to consume materials to make new items?
Crafting is actually on my to-do list as well, and using furnaces for it is an excellent idea! I'm still puzzling out how to implement it in a balanced and fun way. Ideally, it would allow for harder challenges late game, since players can prepare for them specifically by crafting items to deal with them. There could even be normally unobtainable items which can only be obtained by wishing or crafting them with a specific set of materials and a recipe.
> Cthulhu
Regardless of whether I add Cthulhu, I'm going to do something with the high priest of Moloch in the future. I think I've used a wand of death on him in almost every game I've ever played, then immediately grabbed the amulet. It's not a terribly exciting or interesting fight.

**Comment by transcendreamer** [comment]
Good day, dear NullCGT,

I thought, maybe you will find this idea interesting:

There is a patch for SlashEM named SLethe which contains special branch Lethe Gorge and Cthulhu's Sanctum (https://nethackwiki.com/wiki/SLethe) 

The idea is to make a special thematic branch from Lethe Gorge and Cthulhu's Sanctum and put all Lovecraftian monsters there, including those from SlashEM code: deep ones, mi-go, shoggoths, nightgaunts, etc (https://nethackwiki.com/wiki/H.P._Lovecraft) and Cthulhu at the very end of the branch.

They should be happy to live all together in one cosy dreadful place ))) and at least it makes sense for their existence in the game.

Just the idea. 
With best regards.

**Comment by NullCGT** [comment]
My life has been busy, and I haven't touched SpliceHack in a while, so I have to fix at least one segfault before doing anything else. The wiki on this page has a few of the features I'm planning on.
That said, I really like the idea of making a lethe branch. It would let me add the missing lovecraftian monsters (gugs, mi-go, shoggoths) in a way that does not disrupt the master list of monsters. Also, it would avoid the issues I have with the way SLethe restructures gehennom.

The main consideration is what sort of rewards would the Lethe branch yield. Cthulu is incredibly nasty, so they would have to be guarding something powerful in order to make it worth it for the player to try to fight them.

**Comment by transcendreamer** [comment]
Oh, great, I will be be happy. And thanks for wiki update. Dagon also belongs to lovecraftian horde, by the way. Splicing technique sounds very cool and refreshing! 

Regarding what prize could be guarded by Cthulhu... I was thinking: it could be some kind of artifact item related to The Mythos, and my first thought was Necronomicon - a high level spellbook of death and life magic. For example, to revive a killed pet, or to exchange souls/bodies like Ephraim Waite was doing in "The Thing on the Doorstep". The point is: when the adventurer is heavily wounded and may die soon, he casts a spell to exchange his/her soul with some monster's soul nearby - it means they actually switch body forms and their positions and their HP percentages - so the adventurer now is a new body and in fresh health while the victim monster is now going to die. Also the adventurer's afflictions effects (sliming, stoning, illness, punishment, etc) are also transferred to the victim, and adventurer is now free. I think should is very sadistic and fun ))) Also for obvious reasons the adventurer loses his inventory and now he/she needs to finish off the victim to get his stuff back. Or, alternatively, the player may decide to attack other enemies nearby - just like a possession technique in Dishonored 2 - and after killing them - quickly cast a spell again in reverse direction to get back into his/her original body. It correlates with the Soul Splicing you've mentioned in the wiki but it's actually a Soul Exchange )))

Other lovecraftian artifact candidates are Shining Trapezohedron from "The Haunter of the Dark" or Silver Key from "The Gates of Silver Key".

**Comment by NullCGT** [comment]
As of a few weeks ago, the vampire race is available in SpliceHack.

**Comment by transcendreamer** [comment]
Yes! Thanks, I've tried it already. Cool. You've done a really great amount of work (I see enormous lines of commits notifications). And thank you very much for updating. Splicehack currently is one of the most enhanced variants e.g. with nice usability features and of course wonderful amount of new content. I wish Splicehack could get number one in community's popularity!

By the way, any news on firearms and grenades?

**Comment by NullCGT** [comment]
Thank you for your kind words! :) It's only come so far due to collaborating with many wonderful people and developers.

I had a partially complete implementation of firearms and grenades sitting on my local machine a while ago, but it was incredibly buggy. The bugginess was largely due to the grenade code, which is very closely integrated with 3.4.3 functions. Updating it was much more difficult than I anticipated, so it's gone by the wayside while I address various bug reports.

I have a branch open right now where I'm slowly modifying and adding content from SLASH'EM. When I implement firearms and grenades, I'm likely going to do a major restructuring of the functions, so that they're less of a hassle to work with.

**Comment by transcendreamer** [comment]
I love SLASH'EM and its unique features, which are adding a new challenging and sometimes funny situations (like keys being broken or drug overdose because of unsuccessful medkit usage )))  I really love the way SpliceHack is going with diversity and whole new experience with new roles and races like cartomancers, dragonmasters, merfolks & pirates. And the new enhanced forges (although I could not get food cooked on them yet).

Let me send you best wishes and positive energy and strong spirit with bug fighting and developing your brilliant game variant!

**Comment by RojjaCebolla** [comment]
I support keeping grenades rare, they're very powerful and can trivialize otherwise interesting situations.  So can the wand of death, but at least you have to get all the scary things lined up in one neat row.

[pirate bombs!](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.collectiblesofentertainment.com%2Fgame-of-thrones%2Fpirate-bomb%2Fthumbs%2F500%2F112232033014_1.jpg)

I skimmed this thread, it has a lot of text, sorry if i duplicate any of y'all's thoughts. But perhaps they could be made less game-warping in one or more of these ways:

- only appear in tourist/pirate games
- appear rarely, and only **inside** the castle or below (so they can't be used to trivialize the castle)
- be renamed "bombs" and have a piratical theme
- explode in a + shape instead of a 3x3
- simplify the timer to either always be X turns, or for them to just explode on contact and be timerless

**Comment by transcendreamer** [comment]
> I support keeping grenades rare, they're very powerful and can trivialize otherwise interesting situations. So can the wand of death, but at least you have to get all the scary things lined up in one neat row.

Agree. The way grenades were implemented in Slash'em was too much overbalanced. Grenades/bombs should be something special that player keeps for really tough situation.


> [pirate bombs!](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.collectiblesofentertainment.com%2Fgame-of-thrones%2Fpirate-bomb%2Fthumbs%2F500%2F112232033014_1.jpg)

Cool, it would be very thematic and historically right context.


> I skimmed this thread, it has a lot of text, sorry if i duplicate any of y'all's thoughts. But perhaps they could be made less game-warping in one or more of these ways:

> * only appear in tourist/pirate games
> * appear rarely, and only **inside** the castle or below (so they can't be used to trivialize the castle)
> * be renamed "bombs" and have a piratical theme
> * explode in a + shape instead of a 3x3
> * simplify the timer to either always be X turns, or for them to just explode on contact and be timerless

Maybe some shops below castle selling bombs for a quite high price / or even character could craft bombs from collected materials (like in Assassin's Creed).

**Comment by NullCGT** [comment]
> explode in a + shape instead of a 3x3

I really, really want to do this. Unfortunately, the code to create cross-shaped explosions is complicated enough that I think it might be more trouble than it's worth.

> pirate bombs

I like that *a lot*. What about either renaming grenades to "pirate bombs" when playing as a pirate, or creating a special type of "pirate bomb" grenade?

> shop beneath the castle

This could actually fit in extremely well with the alignment quests that I'm planning...

Good news: I had to rewrite a number of things, but I **finally** have SLASH'EM grenades working (mostly). I'm considering the following modifications to them, as a starting point:
- Applying a grenade does not light the entire stack of grenades at once. It's very unintuitive for new players, and it makes using a stack of grenades a pain in the butt.
- Grenades weigh much, much less. This change is necessary so that they actually fly a decent distance when thrown.
- Grenades sell for significantly less money. In SLASH'EM, it's very easy to cheese shopkeepers by selling a stack of grenades, since they're so expensive.
- Soldiers carry grenades less often, and in smaller quantities, in order to prevent both the hail of grenades flung at the player in the castle level, and the several hundred grenades left over after clearing the castle.

Thoughts? I want to get the basic grenade functionality down before I add any sort of special grenades.

**Comment by RojjaCebolla** [comment]
> I like that _a lot_. What about either renaming grenades to "pirate bombs" when playing as a pirate, or creating a special type of "pirate bomb" grenade?
> 
> Good news: I had to rewrite a number of things, but I **finally** have SLASH'EM grenades working (mostly). I'm considering the following modifications to them, as a starting point:
> 
>     * Applying a grenade does not light the entire stack of grenades at once. It's very unintuitive for new players, and it makes using a stack of grenades a pain in the butt.
> 
>     * Grenades weigh much, much less. This change is necessary so that they actually fly a decent distance when thrown.
> 
>     * Grenades sell for significantly less money. In SLASH'EM, it's very easy to cheese shopkeepers by selling a stack of grenades, since they're so expensive.
> 
>     * Soldiers carry grenades less often, and in smaller quantities, in order to prevent both the hail of grenades flung at the player in the castle level, and the several hundred grenades left over after clearing the castle.
> 
> 
> Thoughts? I want to get the basic grenade functionality down before I add any sort of special grenades.

I think DNH already lights single explosives from stacks, instead of lighting the stack.  I had a LOT of fun with a dwarven anachrononaut because of this, i recommend you try it out!  They start with the dynamite, so you can just chuck it at things on dungeon floor 1.

Here's the patch that introduces dynamite, grenade, etc: https://github.com/Chris-plus-alphanumericgibberish/dNAO/commit/0ad4e2093abd9684eaafab1d259b2ee12e0d730f the arming code looks like it's in src/timeout.c

There's only 4 commits that mention grenades, so it's probably pretty stealable code! https://github.com/Chris-plus-alphanumericgibberish/dNAO/search?q=grenade&type=Commits (and 3 commits that mention dynamite, fwiw, if you like that code better for your "bombs"!)

**Comment by RojjaCebolla** [comment]
Also, i like your first 3 of those 4 ideas a lot, though with the re-themeing, i'm less into soldiers having bombs (in part because castle is message-spammy-enough!) and more thinking the bombs would be cool if carried by pirates, rogueish types, quantum mechanics, the occasional lesser demon, etc!

Maybe the floor beneath castle is semi aquatic, and thematically connected to the castle, and has pirate shops - maybe there's a .des you can adapt from https://nethackwiki.com/wiki/The_Sea_(dNetHack)

**Comment by NullCGT** [comment]
Thanks for the link to the dnethack code! 

Hmmm. From a cursory glance, it looks like DNetHack also ported the SLASH'EM code, so applying a stack of grenades will still arm the whole stack, but grenades can be thrown one at a time, which is the same functionality I have currently.

**Comment by RojjaCebolla** [comment]
FWIW, they said

> 13:11 <@riker> firing from the stack will auto arm and throw only 1

but, if the code is too divergent from yours, may as well do your own, i understand that better now!  😅

**Comment by transcendreamer** [comment]
Historically first grenades were not directly related to pirates but rather to infantry and even to cavalry (!) First grenades appear even in 9th century. Chinese incendiary bombs were made of bamboo stem, inside placed a charge of tar and black powder. Chinese thunder crash bombs were made of cast iron with powder and had adjustable fuses. Arabian bombs were made from a glass ball with a mixture of sulfur, nitrate and charcoal, equipped with a wick and a chain. Indian hand bombs could be made of ceramics, terracotta vessels, etc.

Grenades were also used during the Golden Age of Piracy: pirate Captain Thompson used "vast numbers of powder flasks, grenade shells, and stinkpots" to defeat two pirate-hunters sent by the Governor of Jamaica in 1721. Grenadoes were essentially pirate hand-grenades. Also called powder flasks, they were hollow balls of glass or metal which were filled with gunpowder and then fitted with a fuse. Pirates lit the fuse and threw the grenade at their enemies, often with devastating effect. Stinkpots were, as the name suggests, pots or bottles filled with some stinking substance: these were thrown onto the decks of enemy ships in the hope that the fumes would incapacitate the enemies, causing them to vomit and retch.

**Comment by transcendreamer** [comment]
> Good news: I had to rewrite a number of things, but I **finally** have SLASH'EM grenades working (mostly). I'm considering the following modifications to them, as a starting point:
> 
> * Applying a grenade does not light the entire stack of grenades at once. It's very unintuitive for new players, and it makes using a stack of grenades a pain in the butt.
> * Grenades weigh much, much less. This change is necessary so that they actually fly a decent distance when thrown.
> * Grenades sell for significantly less money. In SLASH'EM, it's very easy to cheese shopkeepers by selling a stack of grenades, since they're so expensive.
> * Soldiers carry grenades less often, and in smaller quantities, in order to prevent both the hail of grenades flung at the player in the castle level, and the several hundred grenades left over after clearing the castle.
> 
> Thoughts? I want to get the basic grenade functionality down before I add any sort of special grenades.

Great, that's just cool! 

Just a couple of moments to add:

1. because it's very old primitive types of hand bombs so they must dampen if player falls/jumps to the water unless carried inside water protective bag
2. presumably hand bombs must detonate under certain conditions (fire, lightning, etc)

**Comment by transcendreamer** [comment]
By the way - if flintlock pistols and muskets are in the scope of the Splicehack dev plans - the ammunition for these firearms should deteriorate from water as well...

**Comment by NullCGT** [comment]
I'm going to close this PR down, since most of the items in it have been implemented. This has been a wonderful resource though, and I'm going to continue looking at it for ideas. Please feel free to open up further PRs in the future!
