### ISSUE TITLE
Lit and unlit squares are indistinuishable in curses mode

### ISSUE THREAD

**Issue by NullCGT** [NullCGT/SpliceHack#46]
This is a long-standing issue, probably stemming from the initial merge of the curses patch.

**Comment by NullCGT** [comment]
If anyone encounters this, please let me know what settings you are using. Under my terminal settings, Curses mode appears normal.

**Comment by Ardub23** [comment]
I get this problem using PuTTY for Windows. All floor tiles use a dark grey glyph in Curses when `dark_room` is enabled, regardless of whether they're visible to the hero. The attached ZIP contains my SpliceHack settings file and my PuTTY registry file.
[Settings files.zip](https://github.com/NullCGT/SpliceHack/files/4321379/Settings.files.zip)

**Comment by NullCGT** [comment]
Thanks, Ardub!

Hopefully going to get this one ironed out before the next major release.

**Comment by NullCGT** [comment]
Lit corridors resolved in 25c792237d9a09ee180d32619c413caf48f5ce1a.

**Comment by voguelike** [comment]
i just ran into this identical issue and after almost losing hope trying to solve it, i figured out what was causing it!

what fixes it is running putty as a xterm-256color type terminal. xterm, vt100, vt220 all don't work and show all the lit tiles as dark in curses mode.
also this problem only shows up through ssh for some reason which i found out after running splicehack in cmd and another terminal 

not sure if this helps at all or is even necessary to address since it's such a small use case and the workaround is pretty simple, but i wanted to share this just in case anyone else runs into this same problem

**Comment by NullCGT** [comment]
Wow! Great find! Sorry you had to deal with this issue for so long, though.
