### ISSUE TITLE
Monster corpses appear cooked upon dying

### ISSUE THREAD

**Issue by enetics-secker** [NullCGT/SpliceHack#58]
Monsters are randomly cooked when killed with no flame involved.

**Comment by NullCGT** [comment]
Resolved via 77f94ea146d1035def72668e643fbf9f9a2dd70b. Does not break save compatibility.

It turns out that I mangled a bit flag, and in any case where a monster would have been killed with no message (`XKILL_NOMSG`) the game was tripping the burnt corpse flag (`XKILL_BURNT`) as well. This should solve an enormous number of issues related to cooked monster corpses.
