### ISSUE TITLE
Lycanthropy as a starting vampire = pass through bars in animal form

### ISSUE THREAD

**Issue by enetics-secker** [NullCGT/SpliceHack#65]
While my vampire wizard was in werebear form I was able to pass through the iron bars in orctown.  Perhaps change-form thinks I'm becoming a vapor cloud?  It's reproducible only when starting as a vampire - I tried as player race lycanthrope and couldn't reproduce.

**Comment by NullCGT** [comment]
I was fully prepared to be able to unable to duplicate this issue, but to my surprise, I was able to get it to happen in the same situation. As it happens, werebears can naturally pass between iron bars, due to a small tagging error in monst.c that took quite a while to chase down. Yes, this affected all werebears.

Fixed via 9c107316981ed7c01b6b95e3ea38f2cf0bcd50ae, which also fixes numerous other issues with werebears.
