### ISSUE TITLE
Shortcut for Elbereth

### ISSUE THREAD

**Issue by transcendreamer** [NullCGT/SpliceHack#67]
What about adding Ctlr+E shortcut for faster Elbereth engraving? 
It comes from Unnethack & other forks.

**Comment by NullCGT** [comment]
While Ctrl + E for Elbereth is nice, I'm against adding it to SpliceHack. It takes an implicit gameplay mechanic and makes it explicit.

If Vanilla ever implements an Elbereth shortcut, I will follow suit.

**Comment by transcendreamer** [comment]
> It takes an implicit gameplay mechanic and makes it explicit.

Hmm. Yes. Right. I didn't thought about it. Although it's very unlikely now that the real player starting playing nethack doesn't know about E-word.

BWT interesting approach was implemented in Evilhack where the character (not the real player) must learn E-word from inside the game before using it.

**Comment by NullCGT** [comment]
> Although it's very unlikely now that the real player starting playing nethack doesn't know about E-word.

True, which is why I've gone back and and forth on this one in the past. My perspective is also probably biased, since I personally don't like playing with Elbereth. Of my ascensions, at least one is Elberethless entirely, and I believe I only use Elbereth once or twice per game in the others.

> BWT interesting approach was implemented in Evilhack where the character (not the real player) must learn E-word from inside the game before using it.

I really like what K2 did with Elbereth in EvilHack. It's not a mechanic I feel the need to port, but I think it's a fantastic way of integrating gameplay and player knowledge.
