### ISSUE TITLE
Too many damned pirates

### ISSUE THREAD

**Issue by Ardub23** [NullCGT/SpliceHack#73]
I'm playing as an infernal Pirate. Through seemingly no action of my own, the Pirate quest locate level has completely filled with damned pirates, making it impossible to navigate.
![SpliceHack damned pirates](https://user-images.githubusercontent.com/48235540/82502293-0b253500-9ab4-11ea-88e9-86e5e6f190f5.png)
Every time one of them is killed, another immediately (or almost immediately) appears in a cloud of smoke, and I don't know why. It happens even if no other damned pirates are adjacent to me.

**Comment by NullCGT** [comment]
So the good news: This isn't a bug with SpliceHack.

The bad news: This is a bug in Vanilla NetHack, affecting all 3.7-based variants as well as vanilla.

The fix for it went live earlier today, and I pulled it into Splice literally two minutes before I saw this issue. I'll be pinging K2 to update on Hardfought ASAP.

We are in agreement: That is too damn many damned pirates.

**Comment by Ardub23** [comment]
Good to see there's a fix already! I had a backup plan to levelport past them, but it seems that won't be necessary.
