### ISSUE TITLE
Save some effort - you could borrow from dnh/xnh/etc, rather than slash'em

### ISSUE THREAD

**Issue by RojjaCebolla** [NullCGT/SpliceHack#82]
It sounds like porting code from slash'em has been a lot of work.  unnh, dnh, xnh, and others have already borrowed most or all of slash'em's features - using _their_ code might be a lot less effort than going back into the mists of time for ancient slash'em code!
(also, dnh code in particular benefits from all the time demo spends trying to break it with missing pointers and whatnot)

**Comment by NullCGT** [comment]
I actually do this pretty often; pulling from SLASH'EM is, to put it lightly, not fun. The thing is, DNetHack is actually just as difficult to pull from, if not more so. Like Slash'Em, it's based on 3.4.3, which means a large chunk of the code I import has to get rewritten. For example, DNetHack's grenade and firearm code is almost identical to Slash'Em's, since DNetHack originally pulled the code from Slash'Em. Additionally, DNetHack has enough systems and terminology that I am unfamiliar with that it ends up being much more time-consuming to go through.

I already pull features from xNetHack and UnNetHack instead of Slash'Em whenever possible. Splice's version of the moldy corpse patch comes from XNetHack, for example, and the Black Market code comes from Unnethack.

Generally, I only pull from Slash'Em when I need a baseline, or when it's a feature or monster that does not exist in the same form anywhere else.
