### ISSUE TITLE
multishot, elves, orcs, shamurai, and longbow of Diana

### ISSUE THREAD

**Issue by RojjaCebolla** [NullCGT/SpliceHack#87]
i wanna improve the gamefeel of multishot, elves, orcs, and longbow of Diana.  i'm interested in submitting a PR that has some or all of the following changes:

- samurai, elves, and orcs get multishot bonuses based on the _**arrow type**_, not the _**bow type**_, so that DianaBow (and potentially, other nice randomly-generated or artifact bows) work well for them
- artifact launchers just give you +multishot regardless
- an Orc or Infernal who is firing arrows automagically gets a Poison effect on the arrows, _**if**_ they are wielding a cursed launcher
- /me mumbles "something something Gnomes... Crowssbows..."

(inspired by https://github.com/FredrIQ/fiqhack/commit/c95e2c5d46fb68f2b693fbe8a95d9592c040b41b and https://github.com/yrmvgh/FiddleHack/commit/61fce7317a53dd8db54bc3ae1e1a75362e100f24 and https://github.com/NullCGT/SpliceHack/commit/7eb20c9e7ae2ad302a83cee14e0b38eaf4f8012c )

LMK if any of this would be a welcome PR!

**Comment by NullCGT** [comment]
It seems we think alike! The next Splice version has a complete rebalance of artifacts, in preparation for the addition of alignment quests and other more difficult endgame features. A few days ago, I buffed the Longbow of Diana so that it always gives a bonus to multishot and damage:
https://github.com/NullCGT/SpliceHack/commit/95a1d744b307e3c7da52f86bf3721520b3476cd2

> an Orc or Infernal who is firing arrows automagically gets a Poison effect on the arrows, if they are wielding a cursed launcher

I like this for infernals, especially since somehow incentivizing the use of cursed weapons would be an interesting gameplay mechanic. Infernals are pretty strong already, though, so something else might have to give. Maybe they have a disadvantage with blessed weapons, but an advantage with cursed ones? Just an idea.

In any case, I'm not a huge fan of it with orcs. Orcs don't really have an association with curses, so in terms of flavor it strikes me as a little odd.

> "something something Gnomes... Crowssbows..."

Any and all suggestions on race differentiation are welcome. SLASH'EM techniques do a little to help, but most races still play very similarly.

> LMK if any of this would be a welcome PR!

You're always free to open a PR!
