### ISSUE TITLE
Overhaul existing player races

### ISSUE THREAD

**Issue by NullCGT** [NullCGT/SpliceHack#94]
My goal whenever I add a new race is twofold: I want to create a race that is both fun to play, and fosters a different type of gameplay or strategy than currently exists. I would argue that infernals, vampires, and (revised) angels accomplish these goals. The same cannot be said of drow, changelings, lycanthropes and ghouls. One of the goals for the next version of SpliceHack is to overhaul existing races to make them more balanced and more interesting to play. This issue will serve as a place to make suggestions and discuss potential racial changes.

**Changelings**
I originally implemented changelings as a more balanced alternative to doppelgängers. Several community members have stated that changelings are not particularly fun to play for the following reasons, all of which I agree with:
- Polymorphing into something requires getting into melee range of it.
- Polymorphing is extremely limited by energy and level, to the point that it is almost unusable.
- The race is extremely weak, due to their lack of natural regeneration.

Potential resolutions:
- Drop changelings entirely in favor of Doppelgängers, and nerf doppelgänger abilities so that they are not as egregiously overpowered as they are in SLASH'EM.
- Redesign changelings from scratch, with new mechanics.

**Lycanthropes**
Lycanthropes suffer from the same problem that they do in SLASH'EM: Wolf form is inherently inferior to human form in nearly every way. Additionally, lycanthropes in SpliceHack break armor while transforming, which makes them borderline unplayable. The main goal of playing a lycanthrope essentially becomes negating one's lycanthropy.

Potential resolutions:
- Make the player's animal form significantly stronger.
- Allow the player to continue wearing armor while in animal form.

**Drow**
Drow seem interesting on the surface, but lack any real depth. The ability to put creatures to sleep with an unarmed strike, while interesting, quickly grows useless. Once the player is in the midgame, there is nothing to distinguish playing as a drow from playing as an elf.

Potential resolutions:
- Implement some sort of central mechanic to distinguish drow from elves.

**Ghouls**
While the mechanic of using a sewing kit with monster corpses to modify your attacks is interesting, the feature was implemented very quickly, and as such is underdeveloped. Additionally, the limitation on eating only old corpses can make ghouls very annoying to play.

Potential resolutions:
- Flesh out (pun not intended) the sewing kit mechanic more.
- Add ghoul-specific items, such as ghoul-light lanterns.

**Comment by RojjaCebolla** [comment]
Also, infernal, lycanthrope, and vampire all have regeneration, and all have an "evilish / monstrous" flavour.

Vamps have that bite attack - i assumehope that it heals the user a bit like stormbringer does - they could have a bit of an "endurance" game going on, where they keep on healing on, draining things, winning by attrition.

Infernals could lose the regen and have flaming or poisoned arrows when using cursed weapons - maybe a bit of a specialty in winning via "unsportsmanlike" tactics like arrows, traps, CoC, fireball, and maybe even summons?

not sure about lycanthropes.  maybe it should warn the player "ok you can wear armor, but it's really not a good idea".  and maybe the humanoid form should be pretty mediocre and the wolf form should be sicknasty awesome, akin to going "berserk" in DCSS?
thropes having regen just like vamps do, would be a little more special if the regen was only in wolf mode, and ofc hungerless to contrast with the very intense nutrition-seeking game of the vamp....

**Comment by RojjaCebolla** [comment]
> 
>  **Changelings**
> Potential resolutions:
> 
>     * Drop changelings entirely in favor of Doppelgängers, and nerf doppelgänger abilities so that they are not as egregiously overpowered as they are in SLASH'EM.

Maybe it would be a little less rough on 'lings, if you had the option to both #chat with alive ones, or touch the corpse of dead ones, to gain their form?

The no regen thing seems unnecessarily punishing, a changeling player is playing to change form, they'll use their race abilities without this kind of heavyhanded punishing 😉 .  I'm not a fan of throwing in the towel and just using broken Dopples though.  If you're tired of balancing the race, imo, just temporarily disable it until you feel inspired!
 
>     * Make the player's animal form significantly stronger.
>     * Allow the player to continue wearing armor while in animal form.
i wouldn't allow armor, but maybe keeping boots and cloak is okay.
Come on, imagine how cute a wolf in boots looks!
> **Drow**
>     * Implement some sort of central mechanic to distinguish drow from elves.

Well, drow are heckin neat in DNH, especially anachronaut drow.  mb you can just poach some stuff from there.  i love the Black Web powers!

> Ghouls

no feedback from me on ghouls, haven't wanted to figure them out yet!  WoW classic tho 
![image](https://user-images.githubusercontent.com/62170514/87514395-30639900-c648-11ea-948a-33564d755fce.png)

**Comment by copperwater** [comment]
### Lycanthropes
Could make changing forms entirely voluntary via #monster (i.e. taking a Discworld-like approach to lycanthropy versus the classical folklore of lycanthropes being tormented by involuntary transformations). Thereby turning the giant drawback of the race into something that can be used situationally. (This would of course require the alternate form to be buffed in combat quite a bit, and perhaps the race should get wimpy physical stats to disincentivize combat in the base form.) Also might be able to fold in the idea from Druid where your armor melds into you when you transform - perhaps only after you get a moonstone or some other artifact in mid-game?

### Changelings
Discussed on IRC, but will mention it here again, I think kandra from the Mistborn series could be a cool take on this (maybe merging it with the ghoul race). A race that transforms by consuming and assimilating the corpses of things, especially vertebrates. Notable race advantages could be a large amount of natural damage reduction, as they don't really have blood or much in the way of vital organs; high carrying capacity, as they can store items in their flesh; and the ability to assume the shapes of previously assimilated monsters at will (via carrying around their skeletons). I know you said you want to avoid copyright issues, but I think it'd be worth reaching out to ask Brandon and see if he'd be fine with it, because I suspect he would.

The larger design problem with them is pretty much the same for all shapeshifter-type races: won't they just settle on one or two of the apex combat forms once they become available, and have little reason to become anything else? How can this be avoided? No matter what the plan for changelings ends up as, this question needs an answer.
